sudo: required
env:
  - CXX="g++-4.8"
language: node_js
node_js:
- '5.2'
- '4.1'
- '4.0'
before_script:
  - npm install -g gulp
script: gulp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8

before_install:
  # npm shipped with Node.js 0.8 doesn't support carret so let's update it
  - if [ "$TRAVIS_NODE_VERSION" == "0.8" ]; then npm install -g npm; fi